[package]
name = "kv"
version = "0.1.0"
authors = ["Maxim Davydov <maximdavydoff@yandex.ru>"]

[dependencies]
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"